name: 01 - Building Blocks
on: workflow_dispatch

# we have two jobs called echo-hello and echo-goodbye
jobs:
  echo-hello: # this is the job name
    runs-on: ubuntu-latest # which environment to run
    steps:
      - name: Say hello! # step name
        run: echo "Hello, world"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Successful Step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye"
