name: Workflow Events

on: 
  - push
  - workflow_dispatch

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event name: ${{github.event_name}}"